### ISSUE TITLE
How can I run this project?

### ISSUE THREAD

**Issue by agn-7** [verifiedninja/webapp#2]
How can I run this project? I got this error with `go run webapp.go`:

 ```
database.go:60: SQL Driver Error dial tcp 127.0.0.1:3306: connect: connection refused
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x74061f]

goroutine 1 [running]:
github.com/verifiedninja/webapp/shared/database.Connect(0xc0000233a8, 0x5, 0xc000023438, 0x4, 0x0, 0x0, 0xc000023450, 0x5, 0xc000023455, 0x9, ...)
	/home/agn/go/src/github.com/verifiedninja/webapp/shared/database/database.go:64 +0x32f
main.main()
	/home/agn/go/src/github.com/verifiedninja/webapp/webapp.go:41 +0xc8
exit status 2
```

**Comment by josephspurrier** [comment]
Do you have a database running on you computer that you can access? I would suggest docker to quickly set one up:

```bash
# Start an instance of MySQL using Docker
docker run --name=mysql57 -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -d mysql:5.7
```

**Comment by agn-7** [comment]
@josephspurrier I did it with docker, and mysql container is alive, but another error remains even tough:

```
database.go:60: SQL Driver Error Error 1049: Unknown database 'ninja'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x74061f]

goroutine 1 [running]:
github.com/verifiedninja/webapp/shared/database.Connect(0xc0000233a8, 0x5, 0xc000023438, 0x4, 0x0, 0x0, 0xc000023450, 0x5, 0xc000023455, 0x9, ...)
	/home/agn/go/src/github.com/verifiedninja/webapp/shared/database/database.go:64 +0x32f
main.main()
	/home/agn/go/src/github.com/verifiedninja/webapp/webapp.go:41 +0xc8
exit status 2
```

**Comment by josephspurrier** [comment]
Now you can import the MySQL file:

https://github.com/verifiedninja/webapp/blob/master/config/mysql.sql

**Comment by agn-7** [comment]
@josephspurrier How can I do that? I do not have MySQL experience.
Do I copy this config to the container? or execute it?

**Comment by josephspurrier** [comment]
I would recommend downloading HeidiSQL (Windows), Sequel Pro (Mac), or MySQL Workbench (any OS); connect to the DB, and then execute the commands in the SQL file.

**Comment by josephspurrier** [comment]
Or you could run this command to create a temporary docker container that loads in the mysql.sql file:

```bash
cat mysql.sql | docker run --rm -i --network host mysql:5.7 mysql -h 127.0.0.1 -u root
```

**Comment by agn-7** [comment]
@josephspurrier With this command: 

``
~/go/src/github.com/verifiedninja/webapp/config$ cat mysql.sql | docker run --rm -i --network host mysql:5.7 mysql -h 127.0.0.1 -u root
``

I got this error:

`ERROR 1193 (HY000) at line 8: Unknown system variable 'storage_engine'`

**Comment by agn-7** [comment]
@josephspurrier I pass the above problem with using `default_storage_engine` argument instead of `storage_engine` with borrowing from [this SO post](https://stackoverflow.com/a/36322936/3702377).

**Comment by josephspurrier** [comment]
I think when I created this project I used MySQL 5.6 actually. I just tested with these commands on a Mac and this worked:

```bash
mkdir -p ~/dev/src
export GOPATH=~/dev
go get github.com/verifiedninja/webapp
cd ~/dev/src/github.com/verifiedninja/webapp
docker run --name=mysql56 -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -d mysql:5.6
cat config/mysql.sql | docker run --rm -i --network host mysql:5.6 mysql -h 127.0.0.1 -u root
go build
./webapp
```

**Comment by josephspurrier** [comment]
I appreciate you testing out the app and posting the issues!
